name: CI/CD Pipeline for Frontend

on:
    push:
        branches:
            - main

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            # 1. Checkout code từ GitHub
            - name: Checkout Code
              uses: actions/checkout@v4

            # 2. Cấu hình AWS CLI
            - name: Configure AWS CLI
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: ap-southeast-1

            # 3. Build Docker Image
            - name: Build Frontend Docker Image
              run: |
                  docker build -t amazing-fe:latest  .

            # 4. Push Docker Image lên Amazon ECR
            - name: Push Frontend Image to ECR
              run: |
                  aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 171895670589.dkr.ecr.ap-southeast-1.amazonaws.com
                  docker tag amazing-fe:latest 171895670589.dkr.ecr.ap-southeast-1.amazonaws.com/amazing-fe:latest
                  docker push 171895670589.dkr.ecr.ap-southeast-1.amazonaws.com/amazing-fe:latest

            # 5. Update ECS Service
            - name: Update ECS Service
              run: |
                  aws ecs update-service --cluster booking-cluster --service frontend-service --force-new-deployment
